export const introPage = "Have you ever answered a spam call? Have you ever been sent an email with the subject title “Congratulations! You won!” without signing up for anything? Has an ad ever popped up claiming that all you have to do is click a link to win an iPhone? If you answered yes to any of these questions, then you were susceptible to a social engineering attack. \n \nKeep reading to grasp a better understanding of what social engineering is, how it works and how to prevent its attacks!"

export const socialEngineering = "Social engineering might sound like a very complex term which would make us assume that it has got nothing to do with us. However, the fact is almost every single one of us has or has almost been a victim of a social engineering attack. In technical terms, social engineering is the act of manipulating humans into giving up confidential information, spreading malware viruses, and more. In simpler terms, social engineering exploits human error. These hackers may not be the most skilled with computers and coding but they understand how humans work. They bait them into thinking that they have won something or that they are going to jail if the individual does not provide the hacker with the information they ask for. In most cases, they use one’s extreme happiness and excitement, or their fear and worry against them. What their tactics wish to accomplish is to have these humans’ judgement be clouded by their extreme emotions. \n \nYou might have already made the assumption that social engineering attacks pose a huge threat to information security and privacy, which puts you on the right track.\n \nSocial engineering threatens our information security as well as our privacy. Social engineering attacks are executed with the intention of gaining access to our confidential information which makes our information no longer secure and invades our privacy. Therefore, in order to keep our information secure and maintain our privacy, we have to understand how social engineering attacks are carried out and how to avoid falling victim to them.\n \nIn the next section, we will discuss how social engineering works and how social engineers get their victims to give up their information."

export const howItWorks = "Social engineering is a very interesting and subtle way of putting someone’s privacy at risk because attackers do not force their victims to give away information rather they encourage them to do so. In order for an attacker to successfully gain the information they need or inconvenience their victim however they see fit, they have to pick a target audience and research things about them such as how they are motivated or what matters to them. After the attacker has done their research, they can use what they have learned to gain their victim’s trust, putting them in a vulnerable position. Then, they get their victim to do what they want such as give up information, click on a URL, etc. . Another thing to note that was previously mentioned is how the attacker uses the victim’s emotions to cloud their judgement. They tell them emotion inducing information in order to manipulate them. For example, telling the victim that they have won a draw or that there is a warrant out for their arrest. Although those two examples bring about very different emotions, they are both more intense than usual so victims tend to act in the spur of the moment."

export const commonAttacks = "Now that we have an understanding of how social engineering works, we will look at the two most common forms of attack:\n \nPhishing is when the attacker gets their victim to give up information by pretending to be a trusted person. This includes spam calls, emails, text messages. For example, a common one is receiving a call from an attacker claiming that they work at the Canada Revenue Agency, they tell the victim that they have committed tax fraud and that the police are on their way to arrest them if they do not provide their credit card information.\n \nBaiting attackers use an individual’s curiosity against them. This is usually done by telling them that they have won something whether it be through email or in person. Another example of baiting is leaving a USB with a virus on it somewhere public and waiting for a curious individual to take the bait."

export const beLess = "In the past sections, we covered everything you need to know about social engineering. In this section, you will learn how to prevent these attacks from happening to you. Here are some tips & tricks on how to avoid being the victim of a social engineering attack:\n \nEDUCATE yourself on the topic (which you have already done)\n \nASK yourself rational questions, some being:\n \nIs it a reliable source? Can you verify it?\n \nIs it too good to be true?\n \nHow valuable is the information that is being asked of me?\nRESEARCH the source to determine its legitimacy\n \nDo NOT give up information that could be of use to them, like your phone number\n \nAVOID answering calls and emails from unverified or unrecognised contacts\n \nCongratulations! You are now an expert on social engineering."

